# Generated by Django 4.2 on 2025-03-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_created_at_customuser_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="邮箱地址"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                default="00000000000", max_length=15, unique=True, verbose_name="手机号码"
            ),
        ),
    ]
